FROM astral/uv:python3.11-alpine

ENV LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    UV_COMPILE_BYTECODE=1 \
    UV_CACHE_DIR=/root/.cache/uv \
    UV_PYTHON=python3.11

RUN apk add --no-cache \
    ffmpeg \
    tini \
    tzdata

# 设置工作目录
WORKDIR /app

COPY . .

RUN --mount=type=cache,target=/root/.cache/uv \
    uv venv .venv && \
    uv sync

ENV VIRTUAL_ENV=/app/.venv
ENV PATH="/app/.venv/bin:$PATH"

ENTRYPOINT ["/sbin/tini", "--"]

CMD ["uv", "run", "main.py"]
